
language: node_js
node_js:
  - "9"
dist: trusty
addons:
        chrome: stable
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build -- --base-href https://treetender.github.io/SuperTables/
  - npm run test -- --watch=false --browsers=ChromeHeadless --progress=false
  - npm run e2e 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/supertable
  on:
    branch: master
